// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    MoveContain: typeof import('./src/components/magicMove/MoveContain.vue')['default']
    MoveProxy: typeof import('./src/components/magicMove/MoveProxy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
